### ISSUE TITLE
Upload importmagic to pypi

### ISSUE THREAD

**Issue by timothycrosley** [alecthomas/importmagic#1]
Hi @alecthomas, 

I'm planning on making import magic support the flagship feature for isort 4.0, however I noticed that importmagic isn't yet uploaded to the pypi index.

Thanks! 

Tim

**Comment by jorgenschaefer** [comment]
It seems to me as if there are no releases on pypi – that is, importmagic is now registered on pypi, but there is no package to be downloaded:

```
$ pip install importmagic
Downloading/unpacking importmagic
  Could not find any downloads that satisfy the requirement importmagic
Cleaning up...
No distributions at all found for importmagic
```

Am I missing something? Will there be an upload? :-)

**Comment by birkenfeld** [comment]
I've submitted 0.1.0 to PyPI now, just to have a baseline e.g. for elpy.
