### ISSUE TITLE
importmagic converts multiline imports using parenthesis to slashed

### ISSUE THREAD

**Issue by whirm** [alecthomas/importmagic#15]
It should keep whatever style is in use.

Thanks for your amazing work! :)

**Comment by birkenfeld** [comment]
Agreed.

**Comment by whirm** [comment]
@birkenfeld are you planning on working on this anytime soon?
If not, I will try to do it when I have some spare time.

**Comment by birkenfeld** [comment]
Sure, go ahead :)

**Comment by whirm** [comment]
Is it OK if the default is to group by parentheses when there are neither backslash nor parentheses grouped imports? 
Thats the proposed way in [PEP0328](https://www.python.org/dev/peps/pep-0328/#rationale-for-parentheses)

**Comment by birkenfeld** [comment]
Hm, this is probably something we want to have an option for. Something like
```
Imports.set_style(multiline='parenthesis') # or 'backslash' or 'many'
```
More kwargs could be added (ordering by alphabet or by module name length, handling of newlines between imports, ...)
