### ISSUE TITLE
Please unbundle six.py

### ISSUE THREAD

**Issue by jonathanunderwood** [alecthomas/importmagic#23]
During the Fedora package review it was noted that six.py from http://pypi.python.org/pypi/six/ is bundled in importmagic. A diff between the two files shows that the version in importmagic is behind that of the upstream six project. It would be much better practice to remove the bundled six.py and have importmagic require the upstream six project.

**Comment by alecthomas** [comment]
I prefer to leave it in so that importmagic is dependency free.
