### ISSUE TITLE
ImportMagic incorrectly classifying some packages as local

### ISSUE THREAD

**Issue by ChillarAnand** [alecthomas/importmagic#30]
Original issue: https://github.com/jorgenschaefer/elpy/issues/822 

importmagic does not respect PEP8 ordering of imports, but instead mixes up all types of imports (local, third-party, standard library) into one list:
```
import logging
import time
from mymod import AnUncommonName
```
instead of
```
import logging
import time

from mymod import AnUncommonName
```
and
```
import logging
import mymod
import time
```
instead of
```
import logging
import time

import mymod
```
That's a regression to earlier behavior.

**Comment by alecthomas** [comment]
Have you tried deleting and recreating the index?

**Comment by ChillarAnand** [comment]
Yes, after recreating index also, it is giving same results.

**Comment by alecthomas** [comment]
What version of importmagic is this with?

**Comment by ChillarAnand** [comment]
Using latest version `0.1.5`

**Comment by alecthomas** [comment]
I just pushed 0.1.7, give it a try.
