### ISSUE TITLE
`import numpyas np` bug

### ISSUE THREAD

**Issue by kootenpv** [alecthomas/importmagic#31]
I turned it off because it was making

    import numpy as np

into 

    import numpyas np

Which is not workable.

**Comment by ChillarAnand** [comment]
This bug in fixed  in latest version. Please use importmagic=0.1.5

**Comment by kootenpv** [comment]
Cool, I was hoping so! Really looking forward to switch importmagic functionality back on.

**Comment by kootenpv** [comment]
Fixed.
