### ISSUE TITLE
Split tests out into a separate directory, and don't install them

### ISSUE THREAD

**Issue by jonathanunderwood** [alecthomas/importmagic#32]
Currently the tests live under the importmagic directory, which means the test .py files get installed, whereas the .json file doesn't. On the installed system, therefore the installed test .py files aren't really useful.

It would be better (particular from the perspective of a downstream package maintainer) to have the tests and related data living under a separate test directory.

**Comment by alecthomas** [comment]
I probably won't do this, but I'm not against it if someone sends a PR.
