### ISSUE TITLE
Missing 0.1.7 release

### ISSUE THREAD

**Issue by renatoGarcia** [alecthomas/importmagic#33]
On Import Magic GitHub releases page there are only a 0.1.6 release, but at commit 35dc9d021330c3e6855f645aa8ef8e547d774168 it seems like there was a version 0.1.7.

Also related, at https://pypi.python.org/pypi/importmagic/0.1.7 there are a 0.1.7 release version, but some files are with permission 640 instead of 644. That will trigger an error when a normal user to try read the files but he/she doesn't has permission.

**Comment by alecthomas** [comment]
The releases here aren't updated, and I'm almost positive that permissions of the archive have no bearing on the installed permissions. At least, I just tested installing it as root and the permissions were correct.
