### ISSUE TITLE
Read config from setup.cfg?

### ISSUE THREAD

**Issue by ChillarAnand** [alecthomas/importmagic#36]
Importmagic should be able to read settings like `multiline`, `max_columns` from setup.cfg file so that they can be configured on per project basis.

**Comment by ChillarAnand** [comment]
Any updates?

**Comment by alecthomas** [comment]
No, but that does seem like a good idea. I don't have time at the moment, but I'd be happy to accept patches.

**Comment by ChillarAnand** [comment]
I can work on this. Do you have any other ideas?
