### ISSUE TITLE
Disable import reorder

### ISSUE THREAD

**Issue by cryptomaniac512** [alecthomas/importmagic#43]
Hi!

When I do automatic import all imports in module will be automatically reordered. Can I change this behaviour?

(sorry for my bad english)

**Comment by alecthomas** [comment]
No, there is no way to disable import reordering.

**Comment by cryptomaniac512** [comment]
This feature can be implemented?

**Comment by alecthomas** [comment]
I think this would be fairly non-trivial to achieve, but I'd accept a PR that made it an option.
