### ISSUE TITLE
Provide CLI interface to apply import magic on a file?

### ISSUE THREAD

**Issue by ChillarAnand** [alecthomas/importmagic#45]

**Comment by alecthomas** [comment]
Could be useful. I'd accept a patch that made this mojo happen.

**Comment by razzius** [comment]
I opened a PR with my take on an `importmagic` script. It's pretty basic but gets the job done.

Here's what it looks like:

```sh
$ importmagic
usage: importmagic [-h] [--refresh] [--exclude-current-path] file_name
importmagic: error: the following arguments are required: file_name
$ importmagic myfile.py
$ importmagic myfile.py --refresh
```

**Comment by razzius** [comment]
I'm sure one feature people would like would be the ability to say whether or not the file should be overwritten in-place (-i option). In fact it should probably be the default to print rather than overwrite.

**Comment by alecthomas** [comment]
Merged, thanks!
